version: '2'
services:
    web:
        restart: always
        build: .
        ports: 
            - "8001:8000"
        links:
            - db
        volumes:
            - ${PWD}/bytardag/static/js/autocomplete.js:/app/bytardag/static/js/autocomplete.js
        environment:
            - SENTRY_DSN
            - SERVER_NAME
            - SECRET_KEY
            - DATABASE_URI=postgresql+psycopg2://postgres:${DB_PASSWORD}@db/postgres
    db:
        restart: always
        image: postgres:12.4
        expose:
            - "5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
    dbdata:
        driver: local