"""Initial schema.

Revision ID: 864194dc07a1
Revises: 
Create Date: 2020-08-30 15:24:51.834072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "864194dc07a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "sheet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=4), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("closed", sa.DateTime(), nullable=True),
        sa.Column("signed_at", sa.DateTime(), nullable=True),
        sa.Column("owned_by", sa.Integer(), nullable=True),
        sa.Column("signed_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owned_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signed_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sheet", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sheet_closed"), ["closed"], unique=False)
        batch_op.create_index(batch_op.f("ix_sheet_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sheet_signed_at"), ["signed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sheet_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seller", sa.String(length=4), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("sheet_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sheet_id"],
            ["sheet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("row", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_row_seller"), ["seller"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_row_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("row", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_row_timestamp"))
        batch_op.drop_index(batch_op.f("ix_row_seller"))

    op.drop_table("row")
    with op.batch_alter_table("sheet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sheet_timestamp"))
        batch_op.drop_index(batch_op.f("ix_sheet_signed_at"))
        batch_op.drop_index(batch_op.f("ix_sheet_name"))
        batch_op.drop_index(batch_op.f("ix_sheet_closed"))

    op.drop_table("sheet")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    # ### end Alembic commands ###
